name: bdk_flutter
description: A Flutter implementation of the Bitcoin Development Kit.
version: 0.1.4
homepage: https://github.com/LtbLightning/bdk-flutter

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.6.1
  ffi: ^2.0.1
  freezed_annotation: ^2.1.0
  freezed: ^2.1.0+1
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
flutter:
  plugin:
    platforms:
      android:
        package: io.bdk.f.bdk_flutter
        pluginClass: BdkPlugin
      ios:
        pluginClass: BdkPlugin