name: bdk_flutter
description: A new Flutter project.
version: 0.0.2
homepage:

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: ">=2.5.0"


scripts:
  binary-install: dart bin/config.dart

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.0
  path_provider: ^2.0.11
  plugin_platform_interface: ^2.0.2
  dcli: ^1.9.6
  yaml: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: io.bdk.f.bdk_flutter
        pluginClass: BdkPlugin
      ios:
        pluginClass: BdkPlugin