name: bdk_flutter
description: A new Flutter project.
version: 0.0.5
homepage:

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: ">=2.5.0"




dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.0
  path_provider: ^2.0.11
  flutter_rust_bridge: ^1.37.1
  plugin_platform_interface: ^2.0.2
  yaml: ^3.1.0
  ffi: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: io.bdk.f.bdk_flutter
        pluginClass: BdkPlugin
      ios:
        pluginClass: BdkPlugin