name: bdk_flutter
description: A new Flutter project.
version: 0.0.2
homepage:

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.6.1
  ffi: ^1.2.1
  freezed_annotation: ^2.1.0
  freezed: ^2.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0


flutter:
  plugin:
    platforms:
      android:
        package: io.bdk.f.bdk_flutter
        pluginClass: BdkPlugin
      ios:
        pluginClass: BdkPlugin