name: bdk_flutter
description: A Flutter library for the Bitcoin Development Kit(BDK) (https://bitcoindevkit.org/). The bdk library aims to be the core building block for Bitcoin Applications of any kind.
version: 0.2.0
homepage: https://github.com/LtbLightning/bdk-flutter

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.51.0
  ffi: ^2.0.1
  freezed_annotation: ^2.2.0
  freezed: ^2.2.1
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  ffigen: ^7.2.2

flutter:
  plugin:
    platforms:
      android:
        package: io.bdk.f.bdk_flutter
        pluginClass: BdkPlugin
      ios:
        pluginClass: BdkPlugin
