name: bdk_flutter
description: A Flutter library for the Bitcoin Development Kit(bdk) (https://bitcoindevkit.org/)
version: 0.30.0
homepage: https://github.com/LtbLightning/bdk-flutter

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ">1.82.3 <= 1.82.4"
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  mockito: ^5.4.0
  meta: ^1.10.0
  uuid: ^4.2.1
  http: ^1.1.0
  archive: ^3.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^10.0.0
  build_runner: ^2.4.4
  lints: ^3.0.0

flutter:
  assets:
    - assets/

  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
