[package]
name = "rust"
version = "0.1.5"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.60.0"
[dependencies]
rand = "0.8"
bdk = { version = "0.26.0", features = ["all-keys", "use-esplora-ureq", "sqlite-bundled", "rpc"] }
#bdk-ffi = { git = "https://github.com/bitcoindevkit/bdk-ffi", package = "bdk-ffi", branch="master"}
flutter_rust_bridge = "1.60.0"
serde = "1.0.89"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1