[package]
name = "rust"
version = "0.28.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]
[dev-dependencies]
assert_matches = "1.5"

[build-dependencies]
flutter_rust_bridge_codegen = { version = "= 1.75"  }
[dependencies]
rand = "0.8"
bdk = { version = "0.28.0", features = ["all-keys", "use-esplora-ureq", "sqlite-bundled", "rpc"] }
flutter_rust_bridge = { version = "= 1.75"  }
serde = "1.0.89"
serde_json = "1.0.96"
anyhow = "1.0.68"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1