[package]
name = "rust_bdk_ffi"
version = "0.30.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]
[dev-dependencies]
assert_matches = "1.5"

[build-dependencies]
flutter_rust_bridge_codegen = { version = "= 1.82.6"  }
[dependencies]
rand = "0.8"
bdk = { version = "0.28.2", features = ["all-keys", "use-esplora-ureq", "sqlite-bundled", "rpc"] }
flutter_rust_bridge = { version = "= 1.82.6"  }
serde = "1.0.89"
serde_json = "1.0.96"
anyhow = "1.0.68"
lazy_static = "1.4.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
